# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e1d3f1fa6dc03ed9f3944904b3ffb2ba42cd9faadaaa5f1769b680183e813b3d5448bd0c2ddca77caff25f56d9f35aa4d2c37a88f5c9226224cd4fa68b6cf0

test:
  secret_key_base: 4be2e7a302911f55a07cf28a229db15e8a24af74867f9ee783dd81a4d234538da84d185dbfec8837a4e8620d2375b362122c874ef378a19e59b2396e54aee774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
